### ISSUE TITLE
SSL CA certificates not found on fedora

### ISSUE THREAD

**Issue by emmanueltouzery** [aesiniath/http-streams#22]
If I run this test program on fedora 18:
https://dl.dropbox.com/u/22600720/Test.hs

ghc Test.hs -threaded

 The output for me is:
Test: ProtocolError "error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"

 curl and http-conduit on the same computer have no problems therefore I think the CA certificates are present on the computer.

 $ ls -lh /etc/ssl/certs/
total 1.5M
-rw-r--r-- 1 root root 697K Jan  4 19:10 ca-bundle.crt
-rw-r--r-- 1 root root 778K Jan  4 19:10 ca-bundle.trust.crt
-rwxr-xr-x 1 root root  610 Mar 18 22:21 make-dummy-cert
-rw-r--r-- 1 root root 2.2K Mar 18 22:21 Makefile
-rwxr-xr-x 1 root root  829 Mar 18 22:21 renew-dummy-cert

And if in Inconvenience.hs, I change the linux code to this:

```
SSL.contextSetCAFile ctx "/etc/ssl/certs/ca-bundle.crt"
```

 Then it works.

I tracked this in one of the dependencies of http-conduit:
https://github.com/vincenthz/hs-certificate/tree/master/System/Certificate/X509

the Unix.hs version seems to open by hand every file under that certs folder. I guess openSSL will only open single certificates, not bundles, hence the problem?

And finally:
$ ls -l /usr/lib/ssl
ls: cannot access /usr/lib/ssl: No such file or directory

$ ls -l /etc/ssl/certs
lrwxrwxrwx 1 root root 16 Jan 18 21:56 /etc/ssl/certs -> ../pki/tls/certs

**Comment by AdamWill** [comment]
Ran across this while working on related stuff. FWIW, the best practice is probably to first try and use the SSL library's default trust store; platform builds of OpenSSL (and the MacOS X variant, and LibreSSL, and whatever) usually have the correct default trust store location compiled in, and you should just use that. The OpenSSL function to enable use of the default trust store is `SSL_CTX_set_default_verify_paths()` ; I know flat zip about Haskell but I'd expect its wrapper would expose this, openssl wrappers usually do. I believe the best idea ought to be to try and use the default trust store, if that does not work you can look up the common Debian/RHEL paths (why not specifically check the existence of  `/etc/pki/tls/certs/ca-bundle.crt` rather than looking for the `/etc/pki/tls` directory?) as a fallback. If you do that, you delegate the job of knowing about trust store locations to the platform's OpenSSL build, and if a distro locates it somewhere else or decides to move it, you'll be OK.

**Comment by afcowie** [comment]
@AdamWill Hey, thanks Adam. I didn't know about `set_default_verify_paths()`, and thanks for the heads up about a more reliable way to implement this logic. I'll see about this in the next week or two.

AfC

P.S. Now you know some Haskell :)

**Comment by AdamWill** [comment]
No probs :) I wound up writing a more detailed blog post on this stuff (been meaning to do that for a while): https://www.happyassassin.net/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/
